GET localhost:3000/sdgdsgsdg.json
# 404, json 포맷

###

GET localhost:3000/sdgdsgsdg
# 404, html 포맷

###
# 게시글 생성 테스트
POST localhost:3000/fleamarket/articles
Content-Type: application/json

{
  "article": {
    "user_id": "1",
    "title:" : "hello",
    "content" : "hi",
    "price" : 10000,
    "trade_address": "mars",
    "category": "etc_used"
  }
}

###
# 게시글 조회 테스트
GET localhost:3000/fleamarket/articles/1


###
# 잘못된 게시글 조회 테스트
GET localhost:3000/fleamarket/articles/111111111111111111111111
# 404
