###
# 게시글 조회 테스트
GET localhost:3000/fleamarket/articles
Content-Type: application/json

###
# 특정 게시글 조회 테스트
GET localhost:3000/fleamarket/articles/1.json
Content-Type: application/json

###
# 잘못된 게시글 조회 테스트
GET localhost:3000/fleamarket/articles/111111111111111111111111.json
Content-Type: application/json

###
# 게시글 생성 테스트
POST localhost:3000/fleamarket/articles.json
Content-Type: application/json

{
  "user_id": "1",
  "title" : "new",
  "content" : "new",
  "price" : 10000,
  "trade_address": 2,
  "category": "etc_used"
}

###
# 게시글 수정 테스트
PUT localhost:3000/fleamarket/articles/1.json
Content-Type: application/json

{
  "user_id": "1",
  "title" : "modified",
  "content" : "modified",
  "price" : 100000,
  "wanna_trade_address": 2,
  "category": "etc_used"
}

###
# 게시글 삭제 테스트
DELETE localhost:3000/fleamarket/articles/1.json
Content-Type: application/json
