###
# 유저 거래내역 조회
GET localhost:3000/fleamarket/user/trades.json
Content-Type: application/json
Authorization: 1 # 유저 인증정보


###
# 유저 판매내역 조회
GET localhost:3000/fleamarket/user/trades/sell.json
Content-Type: application/json
Authorization: 1 # 유저 인증정보


###
# 유저 구매내역 조회
GET localhost:3000/fleamarket/user/trades/buy.json
Content-Type: application/json
Authorization: 1 # 유저 인증정보

